# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  tags:
    include:
      - '*'
  branches:
    include:
      - 'refs/tags/*'

resources:
  - repo: self

variables:
  buildConfiguration: 'Release'

stages:
  - stage: Build
    displayName: Build and publish package
    jobs:
      - job: Build
        displayName: Build
        steps:
          - bash: |
              tag=$(git tag --sort=-creatordate | head -n 1)
              echo $tag
              echo "##vso[task.setvariable variable=tag;]$tag"
          - task: UseDotNet@2
            displayName: 'Use .NET Core 8.0 SDK'
            inputs:
              packageType: sdk
              version: 8.x
              installationPath: $(Agent.ToolsDirectory)/dotnet
          - task: DotNetCoreCLI@2
            displayName: 'Restore dependencies'
            inputs:
              command: 'restore'
              projects: '$(Build.SourcesDirectory)/dotnet/TranscriptionClient/TranscriptionClient.sln'
          - task: DotNetCoreCLI@2
            displayName: 'Build projects'
            inputs:
              command: 'build'
              projects: '$(Build.SourcesDirectory)/dotnet/TranscriptionClient/TranscriptionClient.sln'
              arguments: '--no-restore --configuration $(BuildConfiguration) /p:ContinuousIntegrationBuild=true'
          - task: NuGetToolInstaller@1
            displayName: 'Install Mono'
          - task: NuGetAuthenticate@1
            displayName: 'NuGet Authenticate'
          - task: DotNetCoreCLI@2
            displayName: 'Pack Transcriptor.Py.Wrapper NuGet package'
            inputs:
              command: 'pack'
              configuration: $(BuildConfiguration)
              packagesToPack: '$(Build.SourcesDirectory)/dotnet/TranscriptionClient/Transcriptor.Py.Wrapper/Transcriptor.Py.Wrapper.csproj'
              packDestination: '$(Build.ArtifactStagingDirectory)'
              versioningScheme: byEnvVar
              versionEnvVar: tag
              verbosityPack: 'Normal'
          - task: NuGetCommand@2
            displayName: 'Publish Transcriptor.Py.Wrapper NuGet package'
            inputs:
              command: 'push'
              packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
              nuGetFeedType: 'external'
              publishFeedCredentials: 'Codehard Token For TranscriptorPyWrapper'