version: '3.10'

services:
  transcription-server:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.gpu
    ports:
      - "9090:9090"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
  client-socket:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.client
    environment:
      TRASCRIPTION_SERVER_ADDR: "192.168.0.98"
      TRANSCRIPTION_SERVER_PORT: "9090"
      CLIENT_ADDR: "0.0.0.0"
      CLIENT_PORT: "8765"
    ports:
      - "8765:8765"