version: '3.10'

services:
  transcription-server:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.gpu
    ports:
      - "9090:9090"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
  client-socket:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.client
    ports:
      - "8765:8765"